### ISSUE TITLE
install_local.sh 编译失败，可能是哪里出错了？

### ISSUE THREAD

**Issue by likesxuqiang** [IoTS-P/SEmu-Fuzz#3]
[ 99%] Bundling unicorn_archive
[100%] Building CXX object CMakeFiles/unicornafl.dir/unicornafl.cpp.o
make[3]: 离开目录“/home/xuqiang8/SEmu/SEmu-Fuzz/AFLplusplus/unicorn_mode/unicornafl/build”
[100%] Built target bundling_target
[100%] Linking CXX static library libunicornafl.a
make[3]: 离开目录“/home/xuqiang8/SEmu/SEmu-Fuzz/AFLplusplus/unicorn_mode/unicornafl/build”
[100%] Built target unicornafl
make[2]: 离开目录“/home/xuqiang8/SEmu/SEmu-Fuzz/AFLplusplus/unicorn_mode/unicornafl/build”
make[1]: 离开目录“/home/xuqiang8/SEmu/SEmu-Fuzz/AFLplusplus/unicorn_mode/unicornafl/build”
./install_local.sh: 第 50 行： cd: ./unicorn/build/: 没有那个文件或目录
make: *** 没有规则可制作目标“install”。 停止。

**Comment by shandianchengzi** [comment]
不好意思这个文件夹应该创建一下的，mkdir指令没有写进去，很奇怪，这个问题居然现在才被发现。我刚刚更新了脚本了。I apologize that this folder should have been created earlier. The "mkdir" command was not included in the script, which is strange. It's surprising that this problem was not discovered earlier. I have just updated the script.
https://github.com/IoTS-P/SEmu-Fuzz/commit/b6e381d8a9ffc2738450ec53b72effee85a9cb4d
